### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [riboseinc/metanorma-model-iso#39]
Convert metanorma IsoDoc StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.
- [PNG.zip](https://github.com/riboseinc/metanorma-model-iso/files/2317183/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-iso/files/2317184/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-iso/files/2317185/SVG.zip)

**Comment by ronaldtse** [comment]
Done in 405a4822f2f9960ee763166b296a8e81486483b6. Thanks @VasBu !
